#!/usr/bin/env python3
"""Diccionari de pronunciacions per a les veus Azure en català i castellà.

Les veus Joana (ca-ES) i Elvira (es-ES) no són "multilingües": llegeixen
qualsevol paraula amb les regles fonètiques del seu propi idioma, també els
noms propis i termes en anglès. Per això aquest mòdul reescriu foneticament
(amb ortografia catalana/castellana) els termes anglesos ABANS d'enviar el
text a Azure, sense tocar mai el guió original que es desa com a transcripció.

Ampliació: cada episodi pot afegir el seu propi diccionari puntual (per al
títol del llibre, l'autor, etc.) a través del camp opcional "pron" del JSON
pendent. Els termes d'aquest mòdul són els que es repeteixen sovint d'un
episodi a l'altre (empreses, conceptes de negoci en anglès...).
"""
import re

# Terme tal com apareix al guió -> aproximació fonètica amb ortografia catalana
DICCIONARI_CA = {
    "Silicon Valley": "Sàilicon Vàli",
    "Harvard": "Hàrvard",
    "Stanford": "Stànford",
    "Massachusetts": "Massatxússets",
    "startup": "estàrtap",
    "startups": "estàrtaps",
    "feedback": "fídbac",
    "marketing": "màrqueting",
    "business": "bíznes",
    "management": "mànagement",
    "leadership": "lídership",
    "mindset": "màindset",
    "benchmark": "bènxmarc",
    "brainstorming": "brènstorming",
    "coworking": "co-uòrquing",
    "freelance": "frílans",
    "machine learning": "maixín lérning",
    "blockchain": "blòcxein",
    "podcast": "pòdcast",
    "streaming": "estríming",
    "Google": "Gúgol",
    "Amazon": "Àmazon",
    "Netflix": "Nètflix",
    "Apple": "Àpol",
    "iPhone": "Àifon",
    "Airbnb": "Erbienbí",
    "Uber": "Úber",
    "LinkedIn": "Línktin",
    "Facebook": "Féisbuc",
    "Twitter": "Tuíter",
    "Microsoft": "Màicrosoft",
    "Excel": "Èxel",
    "Zoom": "Zum",
    "Wharton": "Uòrton",
    "Berkeley": "Bércli",
    "Yale": "Ieil",
    "Princeton": "Prínsston",
    "Silicon": "Sàilicon",
    # Conceptes de management i negoci
    "agile": "àgail",
    "Agile": "Àgail",
    "mindfulness": "màindfulnes",
    "deadline": "dèdlain",
    "deadlines": "dèdlains",
    "networking": "nètuorquing",
    "empowerment": "empàuerment",
    "onboarding": "onbórding",
    "outsourcing": "àutsorsing",
    "insourcing": "ínsorsing",
    "crowdfunding": "cràudfanding",
    "workshop": "uòrxop",
    "workshops": "uòrxops",
    "know-how": "nou-hau",
    "burnout": "bérnaut",
    "wellness": "uèlnes",
    "coaching": "còutxing",
    "mentoring": "mèntoring",
    "roadmap": "ròudmap",
    "milestone": "màilestoun",
    "milestones": "màilestouns",
    "stakeholder": "estéikjolder",
    "stakeholders": "estéikjolders",
    "insight": "ínsait",
    "insights": "ínsaits",
    "framework": "fréimuork",
    "frameworks": "fréimuorks",
    "mindshare": "màindxer",
    "growth hacking": "grouz jàquing",
    "growth": "grouz",
    "hacking": "jàquing",
    "customer": "cústomer",
    "customer success": "cústomer suksés",
    "churn": "txern",
    "engagement": "engéidjment",
    "retention": "ritènxon",
    "onboard": "onbórd",
    "pitch": "pitx",
    "pitches": "pítxes",
    "pitching": "pítxing",
    "elevator pitch": "élevéitor pitx",
    "board": "bord",
    "board meeting": "bord míting",
    "compliance": "compláians",
    "disclaimer": "disquéimer",
    "trade-off": "tréid-of",
    "trade-offs": "tréid-ofs",
    "overhead": "óuverjed",
    "burn rate": "bern réit",
    "runway": "rànuei",
    "bootstrapping": "butstràping",
    "unicorn": "iúnicorn",
    "scale-up": "escéilap",
    "scaleup": "escéilap",
    "spin-off": "espín-of",
    "turnaround": "térnaraund",
    "due diligence": "diu díligens",
    "venture capital": "vèntxur càpital",
    "angel investor": "éinjol invèstor",
    "angel investors": "éinjol invèstors",
    "seed money": "sid móni",
    "cash flow": "càix flou",
    "supply chain": "saplái txein",
    "big data": "big déita",
    "cloud computing": "clàud compiúting",
    "artificial intelligence": "artifíxal intèlidjens",
    "wearable": "uérabol",
    "wearables": "uérabols",
    "gig economy": "guig icónomi",
    # Empreses i marques
    "Tesla": "Tésla",
    "SpaceX": "Spéis Ex",
    "Nike": "Náiqui",
    "IBM": "Ai Bi Em",
    "Intel": "Íntel",
    "Oracle": "Óracol",
    "Salesforce": "Séilsfors",
    "Slack": "Eslac",
    "Dropbox": "Dròpbox",
    "Spotify": "Spótifai",
    "Adobe": "Adóbi",
    "Samsung": "Sàmsung",
    "Sony": "Sóuni",
    "Toyota": "Toiòta",
    "Walmart": "Uólmart",
    "McDonald's": "Mac Dónalds",
    "Starbucks": "Estàrbacs",
    "Disney": "Díznei",
    "Instagram": "Ínstagram",
    "TikTok": "Tíctoc",
    "Snapchat": "Esnàpxat",
    "WhatsApp": "Uòtsap",
    "YouTube": "Iútiub",
    "Android": "Àndroid",
    "Windows": "Uíndous",
    "MacBook": "Mácbuc",
    "iPad": "Àipad",
    "iPod": "Àipod",
    "Kindle": "Quíndol",
    "PlayStation": "Pléisteixon",
    "Xbox": "Èxbox",
    "Nintendo": "Nintèndo",
    "Lyft": "Lift",
    "DoorDash": "Dórdax",
    "Zappos": "Zàpos",
    "Kodak": "Còdac",
    "Blockbuster": "Blòcbaster",
    "Circuit City": "Sércuit Síti",
    "Fannie Mae": "Fàni Mei",
    "Motorola": "Motoròla",
    "Kimberly-Clark": "Químberli-Clarc",
    "Walgreens": "Uòlgrins",
    "Dell": "Del",
    "Cisco": "Sísco",
    "Twitch": "Tuítx",
    "Reddit": "Rédit",
    "Pinterest": "Pínterest",
    "Craigslist": "Créigslist",
    "Groupon": "Grúpon",
    "Yelp": "Ièlp",
    "Shopify": "Xópifai",
    "Stripe": "Estràip",
    "GitHub": "Guíthab",
    "GitLab": "Guítlab",
    "Figma": "Fígma",
    "Notion": "Nóuxon",
    "Asana": "Asàna",
    "Trello": "Trélou",
    "Zendesk": "Zéndesc",
    "HubSpot": "Hàbspot",
    "Mailchimp": "Méiltximp",
    # Fundadors i executius sovint citats
    "Steve Jobs": "Estíu Yobs",
    "Bill Gates": "Bil Guéits",
    "Gates": "Guéits",
    "Fundació Gates": "Fundació Guéits",
    "Gates Foundation": "Guéits Fàundeixon",
    "Melinda Gates": "Melinda Guéits",
    "Jeff Bezos": "Yef Bézos",
    "Mark Zuckerberg": "Marc Zúcarberg",
    "Warren Buffett": "Uóren Báfet",
    "Richard Branson": "Rítxard Brànson",
    "Larry Page": "Làri Peitx",
    "Sergey Brin": "Serguéi Brin",
    "Reed Hastings": "Rid Jéstings",
    "Sheryl Sandberg": "Xéril Sàndberg",
    "Satya Nadella": "Sàtia Nadèl·la",
    "Tim Cook": "Tim Cuc",
    "Sundar Pichai": "Sàndar Pitxài",
    "Jack Welch": "Yac Uélx",
    # Autors i llibres del catàleg (per si es tornen a esmentar)
    "Ethan Mollick": "Íthan Mòlic",
    "John Doerr": "Yon Dor",
    "Jim Collins": "Yim Còlins",
    "Daniel Kahneman": "Dàniel Càhneman",
    "Kahneman": "Càhneman",
    "Clayton Christensen": "Cléiton Crístensen",
    "Christensen": "Crístensen",
    "Eric Ries": "Éric Ris",
    "Peter Drucker": "Píter Drúcar",
    "Drucker": "Drúcar",
    "Amy Edmondson": "Éimi Édmonson",
    "Andy Grove": "Àndi Gròuv",
    "Reed Hastings": "Rid Jéstings",
    "Erin Meyer": "Érin Màier",
    "Stephen Covey": "Estífen Còvi",
    "Kim Scott": "Quim Escòt",
    "Chan Kim": "Txan Quim",
    "Renée Mauborgne": "Renéi Mobórn",
    "Patrick Lencioni": "Pàtric Lensiòni",
    "Jocko Willink": "Yòco Uílinc",
    "Leif Babin": "Lif Bèibin",
    "Peter Thiel": "Píter Tiel",
    "No Rules Rules": "Nou Rulls Rulls",
    "Blue Ocean Strategy": "Blu Óuxon Estràtegi",
    "Radical Candor": "Ràdical Càndor",
    "Extreme Ownership": "Ecstrím Óunership",
    "Good to Great": "Gud tu Grèit",
    "Zero to One": "Zírou tu Uán",
    "The Lean Startup": "Da Lin Estàrtap",
    "Thinking, Fast and Slow": "Zínquin Fast an Slou",
    "The Innovator's Dilemma": "Da Ínovéitors Dailèma",
    "Right Kind of Wrong": "Ràit Càind ov Ron",
    "High Output Management": "Rai Àutput Mànagement",
    "Co-Intelligence": "Cóu-Intèlidjens",
    "Measure What Matters": "Mèjur Uat Màters",
    "PayPal": "Péi-Pal",
    "LinkedIn": "Línktin",
    "Palantir": "Pàlantir",
    "Elon Musk": "Íilon Mask",
}

DICCIONARI_ES = {
    "Silicon Valley": "Sáilicon Váli",
    "Harvard": "Járvard",
    "Stanford": "Stánford",
    "Massachusetts": "Masachúsets",
    "startup": "estartap",
    "startups": "estartaps",
    "feedback": "fídbac",
    "marketing": "márquetin",
    "business": "bísnes",
    "management": "mánagement",
    "leadership": "lídership",
    "mindset": "máindset",
    "benchmark": "bénchmarc",
    "brainstorming": "brenstorming",
    "coworking": "cowórquin",
    "freelance": "frílans",
    "machine learning": "machín lérnin",
    "blockchain": "blóckchéin",
    "podcast": "pódcast",
    "streaming": "estríming",
    "Google": "Gúgol",
    "Amazon": "Ámazon",
    "Netflix": "Nétflix",
    "Apple": "Ápol",
    "iPhone": "Áifon",
    "Airbnb": "Erbienbí",
    "Uber": "Úber",
    "LinkedIn": "Línktin",
    "Facebook": "Féisbuc",
    "Twitter": "Tuíter",
    "Microsoft": "Máicrosoft",
    "Excel": "Éxel",
    "Zoom": "Zum",
    "Wharton": "Uárton",
    "Berkeley": "Bércli",
    "Yale": "Iéil",
    "Princeton": "Prínston",
    "Silicon": "Sáilicon",
    # Conceptos de management y negocio
    "agile": "áchail",
    "Agile": "Áchail",
    "mindfulness": "máindfulnes",
    "deadline": "dédlain",
    "deadlines": "dédlains",
    "networking": "nétuorquin",
    "empowerment": "empáuerment",
    "onboarding": "onbórdin",
    "outsourcing": "áutsorsin",
    "insourcing": "ínsorsin",
    "crowdfunding": "cráudfandin",
    "workshop": "uórkchop",
    "workshops": "uórkchops",
    "know-how": "nóu-jáu",
    "burnout": "bérnaut",
    "wellness": "uélnes",
    "coaching": "cóutchin",
    "mentoring": "méntorin",
    "roadmap": "róudmap",
    "milestone": "máilestoun",
    "milestones": "máilestouns",
    "stakeholder": "estéikjolder",
    "stakeholders": "estéikjolders",
    "insight": "ínsait",
    "insights": "ínsaits",
    "framework": "fréimuork",
    "frameworks": "fréimuorks",
    "growth hacking": "gróuz jáquin",
    "growth": "gróuz",
    "hacking": "jáquin",
    "customer": "cústomer",
    "customer success": "cústomer sucsés",
    "churn": "chern",
    "engagement": "engéichment",
    "retention": "ritenchon",
    "onboard": "onbórd",
    "pitch": "pitch",
    "pitches": "pítches",
    "pitching": "pítchin",
    "elevator pitch": "élevéitor pitch",
    "board": "bord",
    "board meeting": "bord mítin",
    "compliance": "compláians",
    "disclaimer": "disquéimer",
    "trade-off": "tréid-of",
    "trade-offs": "tréid-ofs",
    "overhead": "óuverjed",
    "burn rate": "bern réit",
    "runway": "rónuei",
    "bootstrapping": "butstrápin",
    "unicorn": "iúnicorn",
    "scale-up": "escéilap",
    "scaleup": "escéilap",
    "spin-off": "espín-of",
    "turnaround": "térnaraund",
    "due diligence": "diú dílichens",
    "venture capital": "véntchur cápital",
    "angel investor": "éinyol invéstor",
    "angel investors": "éinyol invéstors",
    "seed money": "sid móni",
    "cash flow": "cach flóu",
    "supply chain": "sapláy chéin",
    "big data": "big déita",
    "cloud computing": "cláud compiútin",
    "artificial intelligence": "artifíchal intélichens",
    "wearable": "uérabol",
    "wearables": "uérabols",
    "gig economy": "guig icónomi",
    # Empresas y marcas
    "Tesla": "Tésla",
    "SpaceX": "Spéis Ex",
    "Nike": "Náiqui",
    "IBM": "Ai Bi Em",
    "Intel": "Íntel",
    "Oracle": "Óracol",
    "Salesforce": "Séilsfors",
    "Slack": "Eslac",
    "Dropbox": "Dróbox",
    "Spotify": "Spótifai",
    "Adobe": "Adóbi",
    "Samsung": "Sámsung",
    "Sony": "Sóuni",
    "Toyota": "Toyóta",
    "Walmart": "Uólmart",
    "McDonald's": "Mac Dónalds",
    "Starbucks": "Estárbacs",
    "Disney": "Dísnei",
    "Instagram": "Ínstagram",
    "TikTok": "Tíctoc",
    "Snapchat": "Esnápchat",
    "WhatsApp": "Uátsap",
    "YouTube": "Iútiub",
    "Android": "Ándroid",
    "Windows": "Uíndous",
    "MacBook": "Mácbuc",
    "iPad": "Áipad",
    "iPod": "Áipod",
    "Kindle": "Quíndol",
    "PlayStation": "Pléisteichon",
    "Xbox": "Éxbox",
    "Nintendo": "Nintendo",
    "Lyft": "Lift",
    "DoorDash": "Dórdach",
    "Zappos": "Zápos",
    "Kodak": "Códac",
    "Blockbuster": "Blóckbaster",
    "Circuit City": "Sércuit Síti",
    "Fannie Mae": "Fáni Mei",
    "Motorola": "Motorola",
    "Kimberly-Clark": "Químberli-Clarc",
    "Walgreens": "Uálgrins",
    "Dell": "Del",
    "Cisco": "Sísco",
    "Twitch": "Tuích",
    "Reddit": "Rédit",
    "Pinterest": "Pínterest",
    "Craigslist": "Créigslist",
    "Groupon": "Grúpon",
    "Yelp": "Iélp",
    "Shopify": "Chópifai",
    "Stripe": "Estráip",
    "GitHub": "Guítjab",
    "GitLab": "Guítlab",
    "Figma": "Fígma",
    "Notion": "Nóuchon",
    "Asana": "Asána",
    "Trello": "Trélou",
    "Zendesk": "Séndesc",
    "HubSpot": "Jábspot",
    "Mailchimp": "Méilchimp",
    # Fundadores y ejecutivos citados a menudo
    "Steve Jobs": "Estíf Yobs",
    "Bill Gates": "Bil Guéits",
    "Gates": "Guéits",
    "Fundación Gates": "Fundación Guéits",
    "Gates Foundation": "Guéits Fáundeichon",
    "Melinda Gates": "Melinda Guéits",
    "Jeff Bezos": "Yef Bésos",
    "Mark Zuckerberg": "Marc Zúcarberg",
    "Warren Buffett": "Uóren Báfet",
    "Richard Branson": "Ríchard Bránson",
    "Larry Page": "Lári Peich",
    "Sergey Brin": "Serguéi Brin",
    "Reed Hastings": "Rid Jéstings",
    "Sheryl Sandberg": "Chéril Sándberg",
    "Satya Nadella": "Sátia Nadela",
    "Tim Cook": "Tim Cuc",
    "Sundar Pichai": "Sándar Pichái",
    "Jack Welch": "Yac Uélch",
    # Autores y libros del catálogo (por si se vuelven a mencionar)
    "Ethan Mollick": "Íthan Málic",
    "John Doerr": "Yon Dor",
    "Jim Collins": "Yim Cólins",
    "Daniel Kahneman": "Dániel Cáneman",
    "Kahneman": "Cáneman",
    "Clayton Christensen": "Cléiton Crístensen",
    "Christensen": "Crístensen",
    "Eric Ries": "Éric Rís",
    "Peter Drucker": "Píter Drúcar",
    "Drucker": "Drúcar",
    "Amy Edmondson": "Éimi Édmonson",
    "Andy Grove": "Ándi Gróuv",
    "Reed Hastings": "Rid Jéstings",
    "Erin Meyer": "Érin Máier",
    "Stephen Covey": "Estífen Cóvi",
    "Kim Scott": "Kim Escót",
    "Chan Kim": "Chan Kim",
    "Renée Mauborgne": "Renéi Mobórn",
    "Patrick Lencioni": "Pátric Lensióni",
    "Jocko Willink": "Yóco Uílinc",
    "Leif Babin": "Lif Bábin",
    "Peter Thiel": "Píter Tíel",
    "No Rules Rules": "Nou Rulls Rulls",
    "Blue Ocean Strategy": "Blu Óuchon Estrátechi",
    "Radical Candor": "Rádical Cándor",
    "Extreme Ownership": "Ecstrím Óunership",
    "Good to Great": "Gud tu Gréit",
    "Zero to One": "Zírou tu Uán",
    "The Lean Startup": "De Lín Estártap",
    "Thinking, Fast and Slow": "Zínquin Fast an Slóu",
    "The Innovator's Dilemma": "De Ínoveitors Dailema",
    "Right Kind of Wrong": "Ráit Cáind ov Ron",
    "High Output Management": "Rai Áutput Mánagement",
    "Co-Intelligence": "Cóu-Intélichens",
    "Measure What Matters": "Méchur Uat Máters",
    "PayPal": "Péi-Pal",
    "LinkedIn": "Línktin",
    "Palantir": "Pálantir",
    "Elon Musk": "Íilon Mask",
}


def aplica(text, lang="ca", extra=None):
    """Retorna una còpia del text amb els termes anglesos reescrits
    foneticament, per fer-la servir NOMÉS a l'entrada de la veu (mai es
    desa enlloc). `extra` és un diccionari opcional propi de l'episodi
    (p.ex. títol del llibre o nom de l'autor) que té prioritat."""
    base = dict(DICCIONARI_CA if lang.startswith("ca") else DICCIONARI_ES)
    if extra:
        base.update(extra)
    # Les entrades de diverses paraules es substitueixen abans que les
    # paraules soltes, per evitar substitucions parcials incorrectes.
    for original in sorted(base, key=len, reverse=True):
        replacement = base[original]
        pattern = re.compile(r'\b' + re.escape(original) + r'\b')

        def repl(m, replacement=replacement):
            if m.group(0)[0].isupper():
                return replacement[0].upper() + replacement[1:]
            return replacement

        text = pattern.sub(repl, text)
    return text
